jobs:
  - name: hello-world-job
    plan:
      - task: hello-world-task
        config:
          # Tells Concourse which type of worker this task should run on
          platform: linux
          # This is one way of telling Concourse which container image to use for a
          # task. We'll explain this more when talking about resources
          image_resource:
            type: registry-image
            source:
              repository: busybox # images are pulled from docker hub by default
          # Add "the-artifact" to our task
          outputs:
              - name: the-artifact
          run:
            # Change the command to `ls -lF` to see
            # what the task sees in its working directory
            path: ls
            args: [ "-lF" ]