resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/tomekomel/nestjs-playground.git

jobs:
  - name: hello-world-job
    plan:
      - get: repo
        trigger: true   # tell Concourse to trigger this job when new versions are emitted
      - task: hello-world-task
        config:
          # Tells Concourse which type of worker this task should run on
          platform: linux
          # This is one way of telling Concourse which container image to use for a
          # task. We'll explain this more when talking about resources
          image_resource:
            type: registry-image
            source:
              repository: busybox # images are pulled from docker hub by default
          inputs: # add the get step as an input to this task
            - name: repo
          # Add "the-artifact" to our task
          outputs:
              - name: the-artifact
          run:
            path: cat
            args: [ "repo/README.md" ]
